Admin View (Fetch All Interviews API + Frontend) added
rachitshukla08/interview-feedback-app-group-D pull request #1
Opened 2023-08-09 15:45 UTC by rakshitmeshram

Features added 

- [x]  Create API to fetch data from db (Admin)
- [x]  Added dummy frontend(react).
- [x]  Tested CRUD operations on all routes.
- [x]  Setup a dummy db on Atlas.
- [x]  Included CORS and Authentication(disabled) middleware.

Dependencies

- CORS
- dotenv
- express
- mongoose
- mongodb

> Used Vite as a build tool to setup frontend react project

Please review and merge 🤝

2023-08-11 17:07 UTC, PRERNA-CHOUDHARY approved these changes

2023-08-11 17:21 UTC, anuragsati requested changes

2023-08-11 17:21 UTC, anuragsati commented on root/backend/middleware/authenticate.js
> +    const decoded = jwt.verify(token, process.env.JWT_SECRET);
So we might have to authenticate other users as well, in that case, we might need different secrets.
JWT_SECRET is very generic in that sense, we could probably change its name.

2023-08-11 17:21 UTC, anuragsati commented on root/backend/package.json
> +    "app": "node server.js",
Please rename app -> start

2023-08-11 17:21 UTC, anuragsati commented on root/backend/routes/interviewRoutes.js
> +router.delete('/interviews/:id', interviewController.deleteInterview);
These api route matchers will change as discussed earlier

2023-08-11 17:21 UTC, anuragsati commented on root/backend/server.js
> +  console.log(`Server running on http://localhost:${port}`);
PORT will be the env variable in `envConfig.js`
this Message can then be written like this:  `Server running on PORT : {PORT}`

2023-08-11 17:21 UTC, anuragsati commented on root/backend/controllers/interviewController.js
> +    const newInterview = new Interview(req.body);
We should always have some validation on req.body before pushing it to db.
It might happen that req does not have body
In this case, we can check if all required fields are present or not using a validation middleware.
We can also make a builder for creating this object : This will help us when we want to switch from mongo to some other database

2023-08-11 17:21 UTC, anuragsati commented on root/backend/controllers/interviewController.js
> +    const interviews = await Interview.find().sort({dateTime: -1});
Do we have to sort them? Are they not inserted in sorted order?

2023-08-11 17:21 UTC, anuragsati commented on root/backend/controllers/interviewController.js
> +    const skip = (pageNumber - 1) * itemsPerPage;
1 is a magic number here. You can have this logic inside a separate function or have 1 as a static variable which denotes what it is for.

2023-08-11 17:21 UTC, anuragsati commented on root/backend/controllers/interviewController.js
> +// interviewController.js (controllers/interviewController.js)
1. We should have a DAO for accessing the database, generally it is not recommended to have low-level logic in your service layer. You can read about DAO and Layered architecture in MVC. Your controllers should only deal with high-level logic and low-level things like accessing db or calculating skips should be other module's responsibility.
2. We should have middlewares for each controller each might have different validation rules.

2023-08-11 17:32 UTC, rakshitmeshram commented on root/backend/app.js
> +});
Okay, will do that in next iteration.

2023-08-11 17:33 UTC, rakshitmeshram commented on root/backend/app.js
> +app.use('/api', interviewRoutes);
Understood. Can you suggest what we should be moving ahead with ?

2023-08-11 17:33 UTC, rakshitmeshram commented on root/backend/app.js
> +
Okay, will refactor in next iteration.

2023-08-11 17:36 UTC, rakshitmeshram commented on root/backend/config/corsOptions.js
> +    origin: 'http://localhost:5173',
- [x] Added frontend origin to envConfig.js

2023-08-11 17:37 UTC, rakshitmeshram commented on root/backend/middleware/authenticate.js
> +    const decoded = jwt.verify(token, process.env.JWT_SECRET);
Okay, noted.

2023-08-11 17:37 UTC, rakshitmeshram commented on root/backend/package.json
> +    "app": "node server.js",
Okay, done.

2023-08-11 17:37 UTC, rakshitmeshram commented on root/backend/routes/interviewRoutes.js
> +router.delete('/interviews/:id', interviewController.deleteInterview);
Sure.

2023-08-11 17:38 UTC, rakshitmeshram commented on root/backend/middleware/authenticate.js
> +    const decoded = jwt.verify(token, process.env.JWT_SECRET);
Done, changed to YOU_KNOW_WHO

2023-08-11 17:40 UTC, rakshitmeshram commented on root/backend/middleware/authenticate.js
> +    const decoded = jwt.verify(token, process.env.JWT_SECRET);
You decide on naming, my naming convention is out of this world 😅

2023-08-11 17:43 UTC, rakshitmeshram commented on root/backend/server.js
> +  console.log(`Server running on http://localhost:${port}`);
But doing it the way I did, provides a link to open if it doesn't open automatically.

2023-08-11 17:51 UTC, rakshitmeshram commented on root/backend/server.js
> +  console.log(`Server running on http://localhost:${port}`);
Doing it the way I did, provides a link to navigate incase it doesn't open automatically.

2023-08-11 17:52 UTC, rakshitmeshram commented on root/backend/controllers/interviewController.js
> +    const newInterview = new Interview(req.body);
I don't know this stuff. Maybe we can discuss later.

2023-08-11 18:11 UTC, rakshitmeshram commented on root/backend/controllers/interviewController.js
> +    const skip = (pageNumber - 1) * itemsPerPage;
Resolved by turning it into a static variable

2023-08-11 18:12 UTC, rakshitmeshram commented on root/backend/controllers/interviewController.js
> +// interviewController.js (controllers/interviewController.js)
I would like to resurface this issue with @PRERNA-CHOUDHARY

2023-08-11 18:15 UTC, rakshitmeshram commented on root/backend/controllers/interviewController.js
> +    const interviews = await Interview.find().sort({dateTime: -1});
They are inserted in sorted order. I just checked. I left it there in case they was not sorted. 
Removed `.sort({dateTime: -1})`

2023-08-11 18:28 UTC, rakshitmeshram commented on root/backend/app.js
> +});
Done

2023-08-23 06:59 UTC, anuragsati approved these changes

2023-09-04 13:18 UTC, rakshitmeshram commented
Thank You

2023-09-04 13:18 UTC, closed without merging